spring.application.name=fraud-dashboard
spring.datasource.url=jdbc:postgresql://localhost:5432/frauddb
spring.datasource.username=postgres
spring.datasource.password=zaeronib
spring.jpa.hibernate.ddl-auto=none